version: '3'

services:
    server:
        container_name: "mm-server"
        restart: on-failure
        build:
            context: .
            dockerfile: docker/server/prod/Dockerfile
            args:
                serverPort: ${SERVER_PORT}
                serverOrigin: ${EXAMPLE_UI_DOMAIN}
                postgresqlPassword: ${DB_PASSWORD}
        expose:
            - "${SERVER_PORT}"

    example-ui:
       container_name: "mm-example-ui"
       # image: ${IMAGE_TAG}
       restart: on-failure
       environment:
           - NODE_ENV=production
       build:
           # Sets source directory for all COPY, ADD, etc. commands in the Dockerfile
           context: example-ui
           # Path to the dockerfile
           dockerfile: docker/prod/Dockerfile
       ports:
           # Map localhost port to 80 in docker
           - 127.0.0.1:${EXAMPLE_UI_PORT}:80

networks:
    default:
        name: mm-network
        external: true
